applications:
  - args:
      llm_configs:
        - model_loading_config:
            model_id: my_llama
            model_source:
              bucket_uri: s3://air-example-data/meta-Llama-3.2-1B-Instruct
          accelerator_type: A10G
          engine_kwargs:
            max_model_len: 8192
    import_path: ray.serve.llm:build_openai_app
    name: llm-endpoint
    route_prefix: /
